### ISSUE TITLE
Error : Page not found (opencue.io/content/blog/news/spi-case-study.md)

### ISSUE THREAD

**Issue by to09** [AcademySoftwareFoundation/opencue.io#165] opened 2020-03-20 11:24 UTC
[The case study](/docs/concepts/spi-case-study/) link produces error "Page Not Found" in this page opencue.io/content/blog/news/spi-case-study.md .

**Comment by sharifsalah** [comment] 2020-03-20 12:00
Thanks @to09, I'm not seeing the error. This is the link for the blog post:

**Comment by to09** [comment] 2020-03-20 15:18
![Screenshot from 2020-03-20 20-48-14](https://user-images.githubusercontent.com/45192178/77177824-2d1e2d80-6aec-11ea-9244-513f1b7cec31.png)

**Comment by to09** [comment] 2020-03-20 15:20
it works fine in https://www.opencue.io/blog/2019/12/18/sony-pictures-imageworks-case-study/ but in github repo it creates error

**Comment by sharifsalah** [comment] 2020-03-20 15:37
The Markdown links in the opencue.io repo aren't supposed to work. The links only work after the Markdown is converted to HTML and published on opencue.io

I'll close this as 'Working as intended'.

**Closed by sharifsalah** 2020-03-20 15:37 UTC

**Comment by to09** [comment] 2020-03-20 16:43
Ok, Thanks @sharifsalah for the clarification.
